---
title: Lebudo
timezone: Europe/Helsinki
collections:
  pages:
    title: Pages
    output: true
    permalink: /:path
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
timetables_heading: Harjoitusajat syksy 2017
timetables:
- day: Maanantai
  times:
  - 20:00-21:30 Iaido, Lintuvaaran koulu
- day: Tiistai
  times:
  - 20.00-21:30 Kendo, Ruusutorpan koulu
- day: Keskiviikko
  times:
  - 20:00-21:30 Jodo, Lintuvaaran koulu
- day: Torstai
  times:
  - 20:15-21:30 Iaido, Lintuvaaran koulu
- day: Perjantai
  times:
  - 18:00-20:00 Kendo, Postipuun koulu
- day: Lauantai
  times:
  - 14:00-17:00 Iaido / Jodo, Ruusutorpan koulu
- day: Sunnuntai
  times:
  - 13:00-15:00 Kendo, Ruusutorpan koulu
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
